- name : deploying the student war file
  hosts : all
  become_user : root
  vars :
    TOMCAT_LOC : /root/tomcat
  tasks :
     - name : find the old files
       find :
         path : "{{TOMCAT_LOC}}/webapps/"
         file_type : *.*
       register : out
       
     - name : remove the old files
       file :
         path : "{{item.path}}"
         state : absent
       with_items : "{{out.files}}"
       
     - name : print the url value
       get_url :
          url : "{{URL}}"
          dest : "{{TOMCAT_LOC}}/webapps/"
